export const LANDING_PAGE_ICON = {
    Award: "award",
    Building: "building",
    Car: "car",
    Clock: "clock",
    Eye: "eye",
    Gift: "gift",
    Globe: "globe",
    Headset: "headset",
    Heart: "heart",
    Home: "home",
    Leaf: "leaf",
    MapPin: "map-pin",
    Package: "package",
    Shield: "shield",
    Smartphone: "smartphone",
    Sprout: "sprout",
    Star: "star",
    Tree: "tree",
    Truck: "truck",
    Users: "users",
    Wrench: "wrench",
} as const;

export type LandingPageIconName = (typeof LANDING_PAGE_ICON)[keyof typeof LANDING_PAGE_ICON];

export const LANDING_PAGE_ICON_OPTIONS = [
    { value: LANDING_PAGE_ICON.Award, label: "Award" },
    { value: LANDING_PAGE_ICON.Building, label: "Building" },
    { value: LANDING_PAGE_ICON.Car, label: "Car" },
    { value: LANDING_PAGE_ICON.Clock, label: "Clock" },
    { value: LANDING_PAGE_ICON.Eye, label: "Eye" },
    { value: LANDING_PAGE_ICON.Gift, label: "Gift" },
    { value: LANDING_PAGE_ICON.Globe, label: "Globe" },
    { value: LANDING_PAGE_ICON.Headset, label: "Headset" },
    { value: LANDING_PAGE_ICON.Heart, label: "Heart" },
    { value: LANDING_PAGE_ICON.Home, label: "Home" },
    { value: LANDING_PAGE_ICON.Leaf, label: "Leaf" },
    { value: LANDING_PAGE_ICON.MapPin, label: "Map Pin" },
    { value: LANDING_PAGE_ICON.Package, label: "Package" },
    { value: LANDING_PAGE_ICON.Shield, label: "Shield" },
    { value: LANDING_PAGE_ICON.Smartphone, label: "Smartphone" },
    { value: LANDING_PAGE_ICON.Sprout, label: "Sprout" },
    { value: LANDING_PAGE_ICON.Star, label: "Star" },
    { value: LANDING_PAGE_ICON.Tree, label: "Tree" },
    { value: LANDING_PAGE_ICON.Truck, label: "Truck" },
    { value: LANDING_PAGE_ICON.Users, label: "Users" },
    { value: LANDING_PAGE_ICON.Wrench, label: "Wrench" },
] as const;
