#!/usr/bin/env bats
setup() {
  WORK="$BATS_TEST_TMPDIR/p10-qual-$BATS_TEST_NUMBER";mkdir -p "$WORK/evidence"
  COMMIT=$(git rev-parse HEAD);H=$(printf 'a%.0s' {1..64})
  node - "$WORK/gate1.json" "$WORK/gate2.json" "$COMMIT" <<'EOF'
const fs=require('fs'),crypto=require('crypto');const [one,two,commit]=process.argv.slice(2),text=fs.readFileSync('config/trusted-validation-manifest.json','utf8'),manifest=JSON.parse(text),jobs=manifest.requiredJobs.map(j=>({job:j.id,receiptSha256:'a'.repeat(64),artifacts:j.requiredArtifacts.map(path=>({path,bytes:1,sha256:'b'.repeat(64)}))}));for(const [out,id] of [[one,'one'],[two,'two']])fs.writeFileSync(out,JSON.stringify({schemaVersion:1,receiptType:'trusted-validation-gate',status:'success',commit,manifestId:manifest.manifestId,manifestSha256:crypto.createHash('sha256').update(text).digest('hex'),generatedAt:new Date(Math.floor(Date.now()/1000)*1000).toISOString(),run:{id,attempt:'1',repository:'fixture/repo',workflow:'ci'},jobs}));
EOF
  chmod 600 "$WORK/gate1.json" "$WORK/gate2.json"
  node --input-type=module - "$WORK/identity.json" "$COMMIT" "$H" <<'EOF'
import fs from'node:fs';import{createReleaseIdentity}from'./scripts/lib/release-identity.mjs';const[o,c,h]=process.argv.slice(2);fs.writeFileSync(o,JSON.stringify(createReleaseIdentity({releaseVersion:'10.0.0',commitSha:c,repositoryId:'nln/fixture',trustedManifestId:'trusted-v1',trustedManifestSha256:h,immutablePolicyId:'immutable-v1',immutablePolicySha256:h,bundleManifestSha256:h,environmentSchemaSha256:h,migrationMetadataSha256:h,createdAt:'2026-01-01T00:00:00.000Z',scope:'fixture'})));
EOF
  NOW=$(date -u +%Y-%m-%dT%H:%M:%S.000Z)
  node --input-type=module - "$WORK/evidence/component.json" "$COMMIT" "$H" "$NOW" <<'EOF'
import{publishJsonNoOverwrite,receiptEnvelope}from'./scripts/lib/phase10-safe-io.mjs';const[file,commit,h,now]=process.argv.slice(2);publishJsonNoOverwrite(file,receiptEnvelope({receiptType:'release-local-verification',receiptId:'phase10-fixture-local-verification',status:'success',scope:'fixture',command:'release verify-local',release:{version:'10.0.0',commit,releaseId:'phase10-fixture'},policy:{id:'fixture-policy',sha256:h},startedAt:now,finishedAt:now,result:{assuranceProfile:'application',executed:true,application:{status:'success',productionConnectivity:false,databaseRestoreVerified:true,applicationSmokePassed:true}}}));
EOF
  echo "{\"schemaVersion\":1,\"components\":[{\"receiptType\":\"release-local-verification\",\"path\":\"$WORK/evidence/component.json\"}] }" >"$WORK/components.json"
  node scripts/release-evidence.mjs create --identity "$WORK/identity.json" --components "$WORK/components.json" --output "$WORK/evidence/index.json" --now "$NOW"
  for run in one two; do printf '# Validation Receipt\n\nGenerated: %s\nCommit: %s\nBranch:\nWorktree: clean\nValidation command: yarn validate:trusted\n\n## Artifact Check\n\nAll required artifacts for the declared validation command are present and fresh.\n' "$NOW" "$COMMIT" >"$WORK/validation-$run.md"; done
  printf '\nrun-two\n' >>"$WORK/validation-two.md"
  chmod 600 "$WORK/validation-one.md" "$WORK/validation-two.md"
  node scripts/qualify-clean-checkout.mjs --commit "$COMMIT" --receipt-one "$WORK/validation-one.md" --receipt-two "$WORK/validation-two.md" --output "$WORK/clean.json"
  echo '{"status":"success","total":338,"failureInjectionScenarios":[{"id":"pre-mutation","status":"passed"},{"id":"post-activation","status":"passed"}],"fixtureMeasurements":{"downtimeMilliseconds":[0,12],"rollbackRtoMilliseconds":[25]}}' >"$WORK/tests.json"
  node - "$WORK/usability.json" <<'EOF'
const fs=require('fs'),ids=['find-current-release','explain-candidate-production-boundary','diagnose-stale-backup','choose-app-rollback','respond-incompatible-migration','find-release-evidence-chain','identify-downtime-slo'];fs.writeFileSync(process.argv[2],JSON.stringify({status:'passed',independentParticipant:true,exercises:ids.map((id,i)=>({id,status:'passed',durationSeconds:i?30:45,wrongTurns:[],ambiguousWording:[],unsafeSelections:[]}))}));
EOF
  chmod 600 "$WORK/clean.json" "$WORK/tests.json" "$WORK/usability.json"
}
qualify(){ run node scripts/phase10-qualification.mjs --commit "$COMMIT" --trusted-manifest config/trusted-validation-manifest.json --trusted-gate-one "$WORK/gate1.json" --trusted-gate-two "$WORK/gate2.json" --clean-checkout "$WORK/clean.json" --evidence-index "$WORK/evidence/index.json" --test-results "$WORK/tests.json" --usability-results "$WORK/usability.json" --output "$WORK/qualification.json"; }
@test "qualification binds two gates contracts fixture chain tests and usability" { qualify;[ "$status" -eq 0 ];[ "$(stat -c %a "$WORK/qualification.json")" = 600 ];node -e 'const r=require(process.argv[1]);if(r.status!=="qualified"||r.result.productionIntegrationEnabled||r.result.trustedGateReceipts.length!==2||r.result.productionObservations.status!=="skipped"||r.durationMilliseconds<0)process.exit(1)' "$WORK/qualification.json";run node scripts/verify-release-receipt.mjs --receipt "$WORK/qualification.json" --type phase10-qualification --scope fixture --version 10.0.0 --commit "$COMMIT";[ "$status" -eq 0 ]; }
@test "qualification rejects reused gates and non-independent usability" { run node scripts/phase10-qualification.mjs --commit "$COMMIT" --trusted-manifest config/trusted-validation-manifest.json --trusted-gate-one "$WORK/gate1.json" --trusted-gate-two "$WORK/gate1.json" --clean-checkout "$WORK/clean.json" --evidence-index "$WORK/evidence/index.json" --test-results "$WORK/tests.json" --usability-results "$WORK/usability.json" --output "$WORK/reused.json";[ "$status" -ne 0 ];node -e 'const fs=require("fs"),p=process.argv[1],v=require(p);v.independentParticipant=false;fs.writeFileSync(p,JSON.stringify(v))' "$WORK/usability.json";qualify;[ "$status" -ne 0 ]; }
@test "qualification rejects unsafe ambiguous and duplicate supporting evidence" { chmod 644 "$WORK/clean.json";qualify;[ "$status" -ne 0 ];chmod 600 "$WORK/clean.json";node -e 'const fs=require("fs"),p=process.argv[1],v=require(p);v.unexpected=true;fs.writeFileSync(p,JSON.stringify(v))' "$WORK/tests.json";qualify;[ "$status" -ne 0 ];node -e 'const fs=require("fs"),p=process.argv[1],v=require(p);delete v.unexpected;v.failureInjectionScenarios.push(v.failureInjectionScenarios[0]);fs.writeFileSync(p,JSON.stringify(v))' "$WORK/tests.json";qualify;[ "$status" -ne 0 ]; }
