#!/usr/bin/env bats
setup() {
  ROOT="$BATS_TEST_TMPDIR/p10-$BATS_TEST_NUMBER"; mkdir -p "$ROOT/evidence"; NOW=$(date -u +%Y-%m-%dT%H:%M:%S.000Z); COMMIT=$(printf 'a%.0s' {1..40})
  node scripts/tests/fixtures/create-release-lifecycle-fixture.mjs --directory "$ROOT/lifecycle" --version 10.0.0 --commit "$COMMIT" --output "$ROOT/lifecycle.json" --index "$ROOT/lifecycle-index.json" --now "$NOW"
  TRUSTED=$(node -e 'const v=require(process.argv[1]);process.stdout.write(v.components.find(x=>x.receiptType==="trusted-validation-gate").path)' "$ROOT/lifecycle-index.json")
  MIGRATION=$(node -e 'const path=require("path"),v=require(process.argv[1]),p=v.components.find(x=>x.receiptType==="immutable-release-bundle").path;process.stdout.write(path.join(path.dirname(p),"migration-compatibility.json"))' "$ROOT/lifecycle-index.json")
  node - "$ROOT/lifecycle-index.json" "$ROOT/components.json" <<'EOF'
const fs=require('fs'),[indexPath,out]=process.argv.slice(2),index=require(indexPath),ages={'trusted-validation-gate':86400,'runtime-state-backup-qualification':86400,'vps-health-gate':300};fs.writeFileSync(out,JSON.stringify({schemaVersion:1,components:index.components.map(x=>({receiptType:x.receiptType,path:x.path,stage:x.stage,...(ages[x.receiptType]?{maximumAgeSeconds:ages[x.receiptType]}:{})}))}));
EOF
  node --input-type=module - "$ROOT/identity.json" "$ROOT/lifecycle-index.json" "$MIGRATION" "$COMMIT" "$NOW" <<'EOF'
import fs from'node:fs';import crypto from'node:crypto';import{createReleaseIdentity}from'./scripts/lib/release-identity.mjs';const[out,indexPath,migrationPath,commit,createdAt]=process.argv.slice(2),index=JSON.parse(fs.readFileSync(indexPath)),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),bundlePath=index.components.find(x=>x.receiptType==='immutable-release-bundle').path,bundle=JSON.parse(fs.readFileSync(bundlePath)),trusted=JSON.parse(fs.readFileSync('config/trusted-validation-manifest.json')),policy=JSON.parse(fs.readFileSync('config/immutable-release-policy.json'));fs.writeFileSync(out,JSON.stringify(createReleaseIdentity({releaseVersion:'10.0.0',commitSha:commit,repositoryId:'nln/fixture',trustedManifestId:trusted.manifestId,trustedManifestSha256:hash('config/trusted-validation-manifest.json'),immutablePolicyId:policy.policyId,immutablePolicySha256:hash('config/immutable-release-policy.json'),bundleManifestSha256:hash(bundlePath),environmentSchemaSha256:bundle.evidence.environmentSchemaSha256,migrationMetadataSha256:hash(migrationPath),createdAt,scope:'fixture'})),{mode:0o600});
EOF
  cat > "$ROOT/context.json" <<EOF
{"fixture":true,"production":false,"releaseVersion":"10.0.0","commit":"$COMMIT","lifecycleStateReceipt":"$ROOT/lifecycle.json"}
EOF
  export REDUCED_DOWNTIME_FIXTURE_STATE="$ROOT/state.json"
  cat > "$REDUCED_DOWNTIME_FIXTURE_STATE" <<'EOF'
{"services":{"db":{"containerId":"db-1","volumeIds":["db-volume"],"healthy":true},"redis":{"containerId":"redis-1","volumeIds":["redis-volume"],"healthy":true}},"writeSentinel":"preserve-me","log":[]}
EOF
}
prepare_release(){ run node scripts/release.mjs prepare --identity "$ROOT/identity.json" --components "$ROOT/components.json" --migration-metadata "$MIGRATION" --index "$ROOT/evidence/release.index.json" --receipt "$ROOT/evidence/prepare.json" --now "$NOW"; }
@test "all candidate help paths are side-effect free" { before=$(find "$ROOT" -type f | sort); for args in "--help" "prepare --help" "verify-backup --help" "deploy --help" "rollback-app --help" "status --help" "evidence verify --help"; do run node scripts/release.mjs $args; [ "$status" -eq 0 ]; done; after=$(find "$ROOT" -type f | sort); [ "$before" = "$after" ]; }
@test "prepare creates immutable recursively verifiable evidence" { prepare_release; [ "$status" -eq 0 ]; [ "$(stat -c %a "$ROOT/evidence/prepare.json")" = 600 ]; run node scripts/release.mjs evidence verify --index "$ROOT/evidence/release.index.json" --now "$NOW"; [ "$status" -eq 0 ]; }
@test "component swapping is rejected" { prepare_release; echo '{}' > "$TRUSTED"; run node scripts/release.mjs evidence verify --index "$ROOT/evidence/release.index.json" --now "$NOW"; [ "$status" -ne 0 ]; [[ "$output" == *"hash mismatch"* ]]; }
@test "deploy defaults to a zero-mutation plan bound to prepare" { prepare_release; run node scripts/release.mjs deploy --prepare "$ROOT/evidence/prepare.json" --index "$ROOT/evidence/release.index.json" --receipt "$ROOT/evidence/deploy.json" --now "$NOW"; [ "$status" -eq 0 ]; node -e 'const r=require(process.argv[1]);if(r.status!=="planned"||r.productionMutation||r.databaseMutationOccurred)process.exit(1)' "$ROOT/evidence/deploy.json"; }
@test "deploy rejects forged prepare policy evidence" { prepare_release; node -e 'const fs=require("fs"),p=process.argv[1],v=require(p);v.policy.sha256="c".repeat(64);fs.writeFileSync(p,JSON.stringify(v),{mode:0o600})' "$ROOT/evidence/prepare.json"; run node scripts/release.mjs deploy --prepare "$ROOT/evidence/prepare.json" --index "$ROOT/evidence/release.index.json" --receipt "$ROOT/evidence/deploy.json" --now "$NOW"; [ "$status" -ne 0 ]; [ ! -e "$ROOT/evidence/deploy.json" ]; }
@test "full fixture prepare deploy and evidence workflow succeeds" { prepare_release;ID=$(node -e 'process.stdout.write(require(process.argv[1]).release.releaseId)' "$ROOT/evidence/prepare.json");run node scripts/release.mjs deploy --prepare "$ROOT/evidence/prepare.json" --index "$ROOT/evidence/release.index.json" --receipt "$ROOT/evidence/deploy.json" --execute --fixture --confirm "DEPLOY-FIXTURE-$ID" --adapter scripts/tests/fixtures/reduced-downtime-adapter.mjs --context "$ROOT/context.json" --now "$NOW";[ "$status" -eq 0 ];node -e 'const r=require(process.argv[1]);if(r.status!=="success"||r.productionMutation||r.databaseMutationOccurred||r.failure)process.exit(1)' "$ROOT/evidence/deploy.json";run node scripts/release.mjs evidence verify --index "$ROOT/evidence/release.index.json" --now "$NOW";[ "$status" -eq 0 ]; }
@test "post-activation failure emits actionable top-level diagnostic evidence" { prepare_release;ID=$(node -e 'process.stdout.write(require(process.argv[1]).release.releaseId)' "$ROOT/evidence/prepare.json");node -e 'const fs=require("fs"),p=process.argv[1],s=require(p);s.failOperation="health";fs.writeFileSync(p,JSON.stringify(s))' "$REDUCED_DOWNTIME_FIXTURE_STATE";run node scripts/release.mjs deploy --prepare "$ROOT/evidence/prepare.json" --index "$ROOT/evidence/release.index.json" --receipt "$ROOT/evidence/deploy-failed.json" --execute --fixture --confirm "DEPLOY-FIXTURE-$ID" --adapter scripts/tests/fixtures/reduced-downtime-adapter.mjs --context "$ROOT/context.json" --now "$NOW";[ "$status" -ne 0 ];node -e 'const r=require(process.argv[1]);if(r.status!=="failed"||!r.failure.applicationMutationBegan||r.failure.databaseMutationOccurred||!r.failure.safestNextAction)process.exit(1)' "$ROOT/evidence/deploy-failed.json";[[ "$output" == *"Application mutation began: yes"* ]];[[ "$output" == *"Evidence:"* ]]; }
@test "candidate production execution fails closed" { run node scripts/release.mjs deploy --production --prepare x --index x --receipt x; [ "$status" -ne 0 ]; [[ "$output" == *"Phase 11 cutover has not occurred"* ]]; [ ! -e x ]; }
@test "wrong release and stale evidence are rejected" { node -e 'const fs=require("fs"),p=process.argv[1],v=require(p);v.commit="c".repeat(40);fs.writeFileSync(p,JSON.stringify(v),{mode:0o600})' "$TRUSTED"; prepare_release; [ "$status" -ne 0 ]; node -e 'const fs=require("fs"),p=process.argv[1],v=require(p);v.commit=process.argv[2];fs.writeFileSync(p,JSON.stringify(v),{mode:0o600})' "$TRUSTED" "$COMMIT"; run node scripts/release.mjs prepare --identity "$ROOT/identity.json" --components "$ROOT/components.json" --migration-metadata "$MIGRATION" --index "$ROOT/evidence/old.index.json" --receipt "$ROOT/evidence/old.prepare.json" --now 2030-01-01T00:00:00.000Z; [ "$status" -ne 0 ]; }
@test "registries are strict and generated reference has no drift" { run node scripts/validate-phase10-contracts.mjs; [ "$status" -eq 0 ]; run node scripts/generate-operator-reference.mjs --check; [ "$status" -eq 0 ]; }
@test "receipt registry rejects unknown verifier implementations" { cp config/receipt-registry.json "$ROOT/receipt-registry.json";node -e 'const fs=require("fs"),p=process.argv[1],v=require(p);v.types[0].semanticVerifier="not-implemented";fs.writeFileSync(p,JSON.stringify(v))' "$ROOT/receipt-registry.json";run env PHASE10_RECEIPT_REGISTRY="$ROOT/receipt-registry.json" node scripts/validate-phase10-contracts.mjs;[ "$status" -ne 0 ];[[ "$output" == *"unsupported semantic verifier"* ]]; }
