#!/usr/bin/env bats
setup(){
  export WORK="$BATS_TEST_TMPDIR/p7-$BATS_TEST_NUMBER"; mkdir -p "$WORK"; export REDUCED_DOWNTIME_FIXTURE_STATE="$WORK/state.json"
  SCRIPT="$BATS_TEST_DIRNAME/../rehearse-reduced-downtime-deploy.mjs"; ADAPTER="$BATS_TEST_DIRNAME/fixtures/reduced-downtime-adapter.mjs"; POLICY="$BATS_TEST_DIRNAME/../../config/reduced-downtime-deployment-policy.json"
  H=$(printf 'a%.0s' {1..64}); COMMIT=$(printf 'b%.0s' {1..40}); NOW=$(date -u +%Y-%m-%dT%H:%M:%S.000Z)
  node scripts/tests/fixtures/create-release-lifecycle-fixture.mjs --directory "$WORK/lifecycle" --version 7.0.0 --commit "$COMMIT" --output "$WORK/lifecycle.json" --now "$NOW"
  echo "{\"fixture\":true,\"production\":false,\"releaseVersion\":\"7.0.0\",\"commit\":\"$COMMIT\",\"bundleManifestSha256\":\"$H\",\"deploymentContextId\":\"fixture-context-7\",\"migrationMetadataSha256\":\"$H\",\"observedDatabaseFactsSha256\":\"$H\",\"postgresMajor\":13,\"lifecycleStateReceipt\":\"$WORK/lifecycle.json\"}" >"$WORK/context.json"
  echo '{"services":{"db":{"containerId":"db-1","volumeIds":["db-volume"],"healthy":true},"redis":{"containerId":"redis-1","volumeIds":["redis-volume"],"healthy":true}},"writeSentinel":"preserve-me","log":[]}' >"$REDUCED_DOWNTIME_FIXTURE_STATE"
}
rehearse(){ run node "$SCRIPT" --adapter "$ADAPTER" --context "$WORK/context.json" --receipt "$WORK/receipt.json" --policy "$POLICY" "$@"; }
@test "default mode plans without activation" { rehearse;[ "$status" -eq 0 ];node -e 'const r=require(process.argv[1]);if(r.status!=="planned"||r.productionMutation)process.exit(1)' "$WORK/receipt.json";run node scripts/verify-release-receipt.mjs --receipt "$WORK/receipt.json" --type reduced-downtime-deployment-rehearsal --version 7.0.0 --commit "$COMMIT";[ "$status" -eq 0 ];node -e 'const fs=require("fs"),p=process.argv[1],r=require(p);r.productionMutation=true;fs.writeFileSync(p,JSON.stringify(r))' "$WORK/receipt.json";run node scripts/verify-release-receipt.mjs --receipt "$WORK/receipt.json" --type reduced-downtime-deployment-rehearsal;[ "$status" -ne 0 ];! grep -q '"op":"activate"' "$REDUCED_DOWNTIME_FIXTURE_STATE"; }
@test "activates server then ui without dependencies and preserves state" { node -e 'let s=require(process.argv[1]);s.outageOnActivate=2;require("fs").writeFileSync(process.argv[1],JSON.stringify(s))' "$REDUCED_DOWNTIME_FIXTURE_STATE";rehearse --execute true --confirm REHEARSE-REDUCED-DOWNTIME-7.0.0;[ "$status" -eq 0 ];node -e 'const r=require(process.argv[1]);if(r.status!=="success"||r.databaseRestored||r.userVisibleDowntimeMilliseconds<0)process.exit(1)' "$WORK/receipt.json";run node scripts/verify-release-receipt.mjs --receipt "$WORK/receipt.json" --type reduced-downtime-deployment-rehearsal --version 7.0.0 --commit "$COMMIT";[ "$status" -eq 0 ];node -e 'const s=require(process.argv[1]),a=s.log.filter(x=>x.op==="activate");if(a.length!==2||a[0].payload.service!=="server"||a[1].payload.service!=="ui"||a.some(x=>!x.payload.noDeps))process.exit(1)' "$REDUCED_DOWNTIME_FIXTURE_STATE"; }
@test "migration failure is pre-activation and does not rollback" { node -e 'let s=require(process.argv[1]);s.failOperation="migration";require("fs").writeFileSync(process.argv[1],JSON.stringify(s))' "$REDUCED_DOWNTIME_FIXTURE_STATE";rehearse --execute true --confirm REHEARSE-REDUCED-DOWNTIME-7.0.0;[ "$status" -eq 1 ];! grep -q '"op":"activate"' "$REDUCED_DOWNTIME_FIXTURE_STATE";! grep -q '"op":"app-rollback"' "$REDUCED_DOWNTIME_FIXTURE_STATE"; }
@test "incomplete preflight fails before activation" { node -e 'let s=require(process.argv[1]);s.omitPreflight="backup";require("fs").writeFileSync(process.argv[1],JSON.stringify(s))' "$REDUCED_DOWNTIME_FIXTURE_STATE";rehearse --execute true --confirm REHEARSE-REDUCED-DOWNTIME-7.0.0;[ "$status" -eq 1 ];! grep -q '"op":"activate"' "$REDUCED_DOWNTIME_FIXTURE_STATE"; }
@test "activation failure rolls back only with compatibility evidence" { node - "$WORK/context.json" "$WORK/compat.json" <<'EOF'
const fs=require('fs');const [contextPath,out]=process.argv.slice(2),c=require(contextPath),now=Date.now();fs.writeFileSync(out,JSON.stringify({schemaVersion:1,receiptType:'migration-rollback-compatibility',status:'success',releaseVersion:c.releaseVersion,commit:c.commit,bundleManifestSha256:c.bundleManifestSha256,deploymentContextId:c.deploymentContextId,classification:'backward-compatible',postgresMajor:c.postgresMajor,appliedMigrations:[],metadataSha256:c.migrationMetadataSha256,observedSha256:c.observedDatabaseFactsSha256,evaluatedAt:new Date(now-1000).toISOString(),expiresAt:new Date(now+60000).toISOString()}));
EOF
node -e 'let c=require(process.argv[1]);c.rollbackCompatibilityReceipt=process.argv[2];require("fs").writeFileSync(process.argv[1],JSON.stringify(c));let s=require(process.argv[3]);s.failOperation="health";require("fs").writeFileSync(process.argv[3],JSON.stringify(s))' "$WORK/context.json" "$WORK/compat.json" "$REDUCED_DOWNTIME_FIXTURE_STATE";rehearse --execute true --confirm REHEARSE-REDUCED-DOWNTIME-7.0.0;[ "$status" -eq 1 ];grep -q '"op":"app-rollback"' "$REDUCED_DOWNTIME_FIXTURE_STATE";node -e 'const r=require(process.argv[1]);if(r.status!=="recovered"||!r.rollbackAttempted)process.exit(1)' "$WORK/receipt.json"; }
@test "activation failure without compatibility evidence cannot rollback" { node -e 'let s=require(process.argv[1]);s.failOperation="health";require("fs").writeFileSync(process.argv[1],JSON.stringify(s))' "$REDUCED_DOWNTIME_FIXTURE_STATE";rehearse --execute true --confirm REHEARSE-REDUCED-DOWNTIME-7.0.0;[ "$status" -eq 1 ];! grep -q '"op":"app-rollback"' "$REDUCED_DOWNTIME_FIXTURE_STATE"; }
@test "protected state identity mutation is rejected" { node -e 'let s=require(process.argv[1]);s.mutateProtectedState=true;require("fs").writeFileSync(process.argv[1],JSON.stringify(s))' "$REDUCED_DOWNTIME_FIXTURE_STATE";rehearse --execute true --confirm REHEARSE-REDUCED-DOWNTIME-7.0.0;[ "$status" -eq 1 ];[[ "$output" == *"protected database or Redis identity changed"* ]]; }
@test "wrong confirmation and receipt overwrite fail closed" { rehearse --execute true --confirm WRONG;[ "$status" -eq 1 ];echo '{}' >"$WORK/receipt.json";rehearse;[ "$status" -eq 1 ]; }
@test "policy cannot enable production integration" { node -e 'let p=require(process.argv[1]);p.productionIntegrationEnabled=true;require("fs").writeFileSync(process.argv[2],JSON.stringify(p))' "$POLICY" "$WORK/policy.json";run node "$BATS_TEST_DIRNAME/../validate-reduced-downtime-policy.mjs" "$WORK/policy.json";[ "$status" -eq 1 ]; }
