#!/usr/bin/env bats
bats_require_minimum_version 1.5.0
load '__testHelper.bash'
SCRIPT="$BATS_TEST_DIRNAME/../verify-runtime-state-database-restore.mjs"
setup() {
    ROOT="$BATS_TMPDIR/restore-$BATS_TEST_NUMBER"; rm -rf "$ROOT"; mkdir -p "$ROOT/bin"; DUMP="$ROOT/dump.sql"; EXPECTED="$ROOT/expected.json"; RECEIPT="$ROOT/evidence/receipt.json"
    printf 'select 1;\n' >"$DUMP"; printf '%s\n' '{"schemaVersion":1,"factsType":"nln-runtime-state-database-facts","postgresServerVersion":"13.12","appliedMigrations":["001_init"],"tables":["_prisma_migrations","image","image_file","users"],"safeRowCounts":{"image_file":3,"users":2},"checks":{"foreign_keys_valid":true,"upload_references_valid":true,"upload_files_present_and_readable":true}}' >"$EXPECTED"; chmod 600 "$DUMP" "$EXPECTED"
    CONTENT_ROOT="$ROOT/content"; mkdir -p "$CONTENT_ROOT/assets/images/plants"; chmod 700 "$CONTENT_ROOT"
    printf 'a' >"$CONTENT_ROOT/assets/images/plants/a.jpg"; printf 'b' >"$CONTENT_ROOT/assets/images/plants/b.jpg"; printf 'c' >"$CONTENT_ROOT/assets/images/plants/c.jpg"
    cat >"$ROOT/bin/docker" <<'SH'
#!/bin/sh
printf '%s\n' "$*" >>"$DOCKER_LOG"
cat >/dev/null
case "$*" in *pg_isready*) exit "${READY_STATUS:-0}";; *"SHOW server_version"*) printf '13.12\n';; *"SELECT migration_name"*) printf '001_init\n';; *"SELECT tablename"*) printf '_prisma_migrations\nimage\nimage_file\nusers\n';; *'count(*) FROM "image_file"'*) printf '3\n';; *'count(*) FROM "users"'*) printf '2\n';; *"pg_constraint"*|*"LEFT JOIN image"*) printf 't\n';; *"SELECT src FROM image_file"*) printf 'plants/a.jpg\nplants/b.jpg\nplants/c.jpg\n';; esac
SH
    chmod +x "$ROOT/bin/docker"; export DOCKER_LOG="$ROOT/docker.log"
}
run_restore() { node "$SCRIPT" --dump "$DUMP" --expected "$EXPECTED" --receipt "$RECEIPT" --content-root "$CONTENT_ROOT" --docker "$ROOT/bin/docker" --ready-attempts 2 --ready-interval-ms 0; }
@test "disposable restore collects facts verifies invariants and cleans up" { run run_restore; [ "$status" -eq 0 ]; assert_output --partial "restore and database invariants verified"; [ "$(stat -c %a "$RECEIPT")" = 600 ]; [ "$(stat -c %a "$RECEIPT.observed.json")" = 600 ]; grep -q 'run -d.*--network none.*--read-only' "$DOCKER_LOG"; grep -q '^rm -f nln-runtime-restore-' "$DOCKER_LOG"; ! grep -q -- '-p ' "$DOCKER_LOG"; }
@test "restore failure fails closed and still removes the disposable container" { export READY_STATUS=1; run run_restore; [ "$status" -ne 0 ]; assert_output --partial "did not become ready"; [ ! -e "$RECEIPT" ]; grep -q '^rm -f nln-runtime-restore-' "$DOCKER_LOG"; }
@test "unsafe inputs and unsupported checks are rejected before Docker" { chmod 644 "$DUMP"; run run_restore; [ "$status" -ne 0 ]; assert_output --partial "must be owner-only"; [ ! -e "$DOCKER_LOG" ]; chmod 600 "$DUMP"; node -e 'const fs=require("fs"),p=process.argv[1],v=require(p);v.checks.external_network=true;fs.writeFileSync(p,JSON.stringify(v));fs.chmodSync(p,0o600)' "$EXPECTED"; run run_restore; [ "$status" -ne 0 ]; assert_output --partial "unsupported integrity check"; [ ! -e "$DOCKER_LOG" ]; }
@test "symlinked dumps existing evidence and non-Postgres images are rejected" { ln -s "$DUMP" "$ROOT/link.sql"; run node "$SCRIPT" --dump "$ROOT/link.sql" --expected "$EXPECTED" --receipt "$RECEIPT" --docker "$ROOT/bin/docker"; [ "$status" -ne 0 ]; assert_output --partial "regular file"; mkdir -p "$(dirname "$RECEIPT")"; printf keep >"$RECEIPT"; run run_restore; [ "$status" -ne 0 ]; assert_output --partial "already exists"; [ "$(cat "$RECEIPT")" = keep ]; rm "$RECEIPT"; run node "$SCRIPT" --dump "$DUMP" --expected "$EXPECTED" --receipt "$RECEIPT" --image latest --docker "$ROOT/bin/docker"; [ "$status" -ne 0 ]; assert_output --partial "only an explicit PostgreSQL"; }
@test "missing upload content fails invariant verification" { rm "$CONTENT_ROOT/assets/images/plants/b.jpg"; run run_restore; [ "$status" -ne 0 ]; assert_output --partial "integrity check failed: upload_files_present_and_readable"; grep -q '^rm -f nln-runtime-restore-' "$DOCKER_LOG"; }
@test "unsafe database upload paths fail invariant verification" { export UPLOAD_REFERENCES='../escape.jpg'; sed -i 's/printf '\''plants\/a.jpg\\nplants\/b.jpg\\nplants\/c.jpg\\n'\''/printf '\''%s\\n'\'' "${UPLOAD_REFERENCES:-plants\/a.jpg}"/' "$ROOT/bin/docker"; run run_restore; [ "$status" -ne 0 ]; assert_output --partial "integrity check failed: upload_files_present_and_readable"; }
@test "upload verification requires a secure real content root before Docker" { chmod 755 "$CONTENT_ROOT"; run run_restore; [ "$status" -ne 0 ]; assert_output --partial "content root must be owner-only"; [ ! -e "$DOCKER_LOG" ]; chmod 700 "$CONTENT_ROOT"; ln -s "$CONTENT_ROOT" "$ROOT/content-link"; run node "$SCRIPT" --dump "$DUMP" --expected "$EXPECTED" --receipt "$RECEIPT" --content-root "$ROOT/content-link" --docker "$ROOT/bin/docker"; [ "$status" -ne 0 ]; assert_output --partial "content root must be a real directory"; [ ! -e "$DOCKER_LOG" ]; }
@test "symlinked upload files and parent directories fail invariant verification" { mv "$CONTENT_ROOT/assets/images/plants/a.jpg" "$ROOT/a.jpg"; ln -s "$ROOT/a.jpg" "$CONTENT_ROOT/assets/images/plants/a.jpg"; run run_restore; [ "$status" -ne 0 ]; assert_output --partial "integrity check failed: upload_files_present_and_readable"; rm "$CONTENT_ROOT/assets/images/plants/a.jpg"; cp "$ROOT/a.jpg" "$CONTENT_ROOT/assets/images/plants/a.jpg"; mv "$CONTENT_ROOT/assets/images/plants" "$CONTENT_ROOT/assets/images/real-plants"; ln -s real-plants "$CONTENT_ROOT/assets/images/plants"; rm -rf "$RECEIPT" "$RECEIPT.observed.json"; run run_restore; [ "$status" -ne 0 ]; assert_output --partial "integrity check failed: upload_files_present_and_readable"; }
