#!/usr/bin/env bats
load "${BATS_TEST_DIRNAME}/__testHelper.bash"
ROOT="${BATS_TEST_DIRNAME}/../.."
setup(){ WORK="$BATS_TMPDIR/p8-$BATS_TEST_NUMBER";mkdir -p "$WORK";chmod +x "$ROOT/scripts/tests/fixtures/vps-health-maintenance-adapter.mjs";export VPS_FIXTURE_STATE="$WORK/state.json";NOW="2026-01-10T00:00:00.000Z";cat >"$VPS_FIXTURE_STATE" <<JSON
{"facts":{"docker":{"reachable":true},"containers":{"ui":{"running":true,"health":"healthy","restarts":0},"server":{"running":true,"health":"healthy","restarts":0},"db":{"running":true,"health":"healthy","restarts":0},"redis":{"running":true,"health":"healthy","restarts":0}},"disks":{"project":{"freeBytes":9000000000,"freeInodes":50000},"docker":{"freeBytes":9000000000,"freeInodes":50000},"backup":{"freeBytes":9000000000,"freeInodes":50000},"database":{"freeBytes":9000000000,"freeInodes":50000}},"postgres":{"ready":true,"readQuery":true,"partialMigrations":false},"redis":{"ping":true,"persistenceError":false},"host":{"recentOomEvents":0,"filesystemErrors":0,"load1":1,"cpuCount":2,"failedSystemdUnits":[],"timeSynchronized":true,"clockOffsetSeconds":0,"pendingReboot":false},"recovery":{"qualifiedBackupAt":"2026-01-09T12:00:00.000Z","remoteCopyQualified":true,"restoreDrillAt":"2026-01-05T00:00:00.000Z"},"network":{"tlsDaysRemaining":40,"publicReachable":true},"packages":{"metadataRefreshedAt":"2026-01-09T12:00:00.000Z"}},"inspect":{"hostFingerprint":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","qualifiedBackup":true,"remoteCopy":true,"restoreEvidence":true},"postHealth":{"status":"passed","databaseHealthy":true,"redisHealthy":true,"publicHealthy":true}}
JSON
}
@test "healthy fixture produces owner-only passing health receipt and only observes" { run node "$ROOT/scripts/evaluate-vps-health.mjs" --adapter "$ROOT/scripts/tests/fixtures/vps-health-maintenance-adapter.mjs" --output "$WORK/health.json" --now "$NOW";assert_success;[ "$(stat -c %a "$WORK/health.json")" = 600 ];node -e 'const r=require(process.argv[1]);if(r.status!=="passed"||r.adapterMode!=="read-only")process.exit(1)' "$WORK/health.json";[ "$(node -e 'const s=require(process.argv[1]);process.stdout.write(s.log.map(x=>x.op).join(","))' "$VPS_FIXTURE_STATE")" = observe ]; }
@test "low inodes and OOM block health" { node -e 'const fs=require("fs"),p=process.argv[1],s=require(p);s.facts.disks.database.freeInodes=1;s.facts.host.recentOomEvents=1;fs.writeFileSync(p,JSON.stringify(s))' "$VPS_FIXTURE_STATE";run node "$ROOT/scripts/evaluate-vps-health.mjs" --adapter "$ROOT/scripts/tests/fixtures/vps-health-maintenance-adapter.mjs" --output "$WORK/health.json" --now "$NOW";assert_failure;node -e 'const r=require(process.argv[1]);if(r.summary.blocking<2)process.exit(1)' "$WORK/health.json"; }
@test "stale backup expiring TLS and failed database block" { node -e 'const fs=require("fs"),p=process.argv[1],s=require(p);s.facts.recovery.qualifiedBackupAt="2025-01-01T00:00:00Z";s.facts.network.tlsDaysRemaining=2;s.facts.postgres.readQuery=false;fs.writeFileSync(p,JSON.stringify(s))' "$VPS_FIXTURE_STATE";run node "$ROOT/scripts/evaluate-vps-health.mjs" --adapter "$ROOT/scripts/tests/fixtures/vps-health-maintenance-adapter.mjs" --output "$WORK/h.json" --now "$NOW";assert_failure; }
@test "sensitive adapter evidence is rejected" { node -e 'const fs=require("fs"),p=process.argv[1],s=require(p);s.facts.apiToken="do-not-print-me";fs.writeFileSync(p,JSON.stringify(s))' "$VPS_FIXTURE_STATE";run node "$ROOT/scripts/evaluate-vps-health.mjs" --adapter "$ROOT/scripts/tests/fixtures/vps-health-maintenance-adapter.mjs" --output "$WORK/h.json" --now "$NOW";assert_failure;refute_output --partial "do-not-print-me";[ ! -e "$WORK/h.json" ]; }
make_inventory(){ node - "$WORK" "$NOW" <<'EOF'
const fs=require('fs'),crypto=require('crypto');const [root,now]=process.argv.slice(2),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),h='c'.repeat(64),commit='d'.repeat(40),policy={id:'fixture-policy',sha256:h},archive={sha256:h,bytes:100};
fs.writeFileSync(`${root}/backup.json`,JSON.stringify({schemaVersion:1,receiptType:'runtime-state-backup-qualification',status:'success',scope:'fixture',release:{version:'8.0.0',commit},finishedAt:now,policy:{id:'nln-runtime-state-backup-policy-v1',sha256:hash('config/runtime-state-backup-policy.json')},inventory:{id:'nln-runtime-state-v1',sha256:hash('config/runtime-state-inventory.json')},archive,databaseRestore:{status:'success',receiptSha256:h,invariantsSha256:h},assuranceStates:['captured','content-verified','database-restore-verified','qualified']}));
fs.writeFileSync(`${root}/remote.json`,JSON.stringify({schemaVersion:1,receiptType:'runtime-state-remote-download-verification',status:'success',scope:'fixture',finishedAt:now,policy,archive}));
fs.writeFileSync(`${root}/restore.json`,JSON.stringify({schemaVersion:1,receiptType:'runtime-state-application-restore-verification',status:'success',scope:'fixture',finishedAt:now,policy,archive}));
EOF
cat >"$WORK/inventory.json" <<JSON
{"fixture":true,"production":false,"hostFingerprint":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","prerequisites":{"qualifiedBackupReceipt":"$WORK/backup.json","remoteDownloadReceipt":"$WORK/remote.json","restoreReceipt":"$WORK/restore.json"},"actions":[{"id":"packages","commandClass":"package-update","reason":"Apply reviewed security updates","destructive":false},{"id":"cache","commandClass":"cleanup","reason":"Remove selected disposable cache","destructive":true,"cleanupClass":"build-cache","recoveryProcedure":"Rebuild cache"},{"id":"dbvol","commandClass":"cleanup","reason":"Unsafe protected volume cleanup","destructive":true,"cleanupClass":"database-volume","recoveryProcedure":"restore"}]}
JSON
}
@test "maintenance planning is dry-run evidence and rejects protected cleanup" { make_inventory;run node "$ROOT/scripts/plan-vps-maintenance.mjs" --inventory "$WORK/inventory.json" --output "$WORK/plan.json" --actions packages,cache --now "$NOW";assert_success;[ "$(stat -c %a "$WORK/plan.json")" = 600 ];run node "$ROOT/scripts/plan-vps-maintenance.mjs" --inventory "$WORK/inventory.json" --output "$WORK/bad.json" --actions dbvol;assert_failure; }
@test "execution requires exact confirmation and unchanged host" { make_inventory;node "$ROOT/scripts/plan-vps-maintenance.mjs" --inventory "$WORK/inventory.json" --output "$WORK/plan.json" --actions packages --now "$NOW";HASH=$(node -e 'process.stdout.write(require(process.argv[1]).planHash)' "$WORK/plan.json");run node "$ROOT/scripts/execute-vps-maintenance.mjs" --plan "$WORK/plan.json" --adapter "$ROOT/scripts/tests/fixtures/vps-health-maintenance-adapter.mjs" --receipt "$WORK/no.json" --execute true --confirm wrong --now "$NOW";assert_failure;run node "$ROOT/scripts/execute-vps-maintenance.mjs" --plan "$WORK/plan.json" --adapter "$ROOT/scripts/tests/fixtures/vps-health-maintenance-adapter.mjs" --receipt "$WORK/yes.json" --execute true --confirm "EXECUTE-MAINTENANCE-$HASH" --now "$NOW";assert_success; }
@test "stale host and failed post-health fail closed with receipt" { make_inventory;node "$ROOT/scripts/plan-vps-maintenance.mjs" --inventory "$WORK/inventory.json" --output "$WORK/plan.json" --actions packages --now "$NOW";HASH=$(node -e 'process.stdout.write(require(process.argv[1]).planHash)' "$WORK/plan.json");node -e 'const fs=require("fs"),p=process.argv[1],s=require(p);s.inspect.hostFingerprint="bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";fs.writeFileSync(p,JSON.stringify(s))' "$VPS_FIXTURE_STATE";run node "$ROOT/scripts/execute-vps-maintenance.mjs" --plan "$WORK/plan.json" --adapter "$ROOT/scripts/tests/fixtures/vps-health-maintenance-adapter.mjs" --receipt "$WORK/r.json" --execute true --confirm "EXECUTE-MAINTENANCE-$HASH" --now "$NOW";assert_failure;node -e 'if(require(process.argv[1]).status!=="failed")process.exit(1)' "$WORK/r.json"; }
