import react from "@vitejs/plugin-react-swc";
import path from "path";
import { defineConfig } from "vitest/config";

export default defineConfig({
    plugins: [react()],
    test: {
        globals: true,
        environment: "jsdom",
        setupFiles: ["./src/setupTests.ts"],
        include: ["src/**/*.{test,spec}.{ts,tsx}"],
        exclude: ["node_modules", "dist", "build"],
        clearMocks: true,
        coverage: {
            provider: "v8",
            reporter: ["text", "json", "json-summary", "html"],
            include: ["src/**/*.{ts,tsx}"],
            thresholds: {
                statements: 16,
                branches: 71,
                functions: 40.8,
                lines: 16,
                "src/api/rest/**/*.{ts,tsx}": {
                    statements: 50,
                    branches: 77,
                    functions: 15,
                    lines: 50,
                },
                "src/route/**/*.{ts,tsx}": {
                    statements: 39,
                    branches: 85,
                    functions: 32,
                    lines: 39,
                },
                "src/stores/**/*.{ts,tsx}": {
                    statements: 89,
                    branches: 76,
                    functions: 83,
                    lines: 89,
                },
                "src/utils/**/*.{ts,tsx}": {
                    statements: 40,
                    branches: 91,
                    functions: 74,
                    lines: 40,
                },
                "src/components/ErrorBoundary/ErrorBoundary.tsx": {
                    statements: 78,
                    branches: 60,
                    functions: 68,
                    lines: 78,
                },
                "src/components/Hero/Hero.tsx": {
                    statements: 98,
                    branches: 51,
                    functions: 100,
                    lines: 98,
                },
                "src/hooks/useDebounce.ts": {
                    statements: 100,
                    branches: 100,
                    functions: 100,
                    lines: 100,
                },
                "src/hooks/useDimensions.ts": {
                    statements: 84,
                    branches: 93,
                    functions: 75,
                    lines: 84,
                },
                "src/hooks/useHistoryState.ts": {
                    statements: 100,
                    branches: 100,
                    functions: 100,
                    lines: 100,
                },
                "src/hooks/useWindowSize.ts": {
                    statements: 100,
                    branches: 100,
                    functions: 100,
                    lines: 100,
                },
                "src/pages/admin/AdminMainPage/AdminMainPage.tsx": {
                    statements: 100,
                    branches: 100,
                    functions: 100,
                    lines: 100,
                },
                "src/pages/admin/adminRoutes.ts": {
                    statements: 100,
                    branches: 100,
                    functions: 100,
                    lines: 100,
                },
                "src/pages/admin/AdminHomepageHeroBanner/heroBannerFormState.ts": {
                    statements: 95,
                    branches: 94,
                    functions: 100,
                    lines: 95,
                },
                "src/utils/csrf.ts": {
                    statements: 80,
                    branches: 78,
                    functions: 88,
                    lines: 80,
                },
            },
            exclude: [
                "node_modules",
                "dist",
                "build",
                "src/**/*.d.ts",
                "src/setupTests.ts",
                "src/test/**",
                "src/__mocks__/**",
                "src/index.tsx",
                "src/**/*.test.{ts,tsx}",
                "src/**/*.spec.{ts,tsx}",
            ],
        },
    },
    resolve: {
        alias: [
            { find: "api", replacement: path.resolve(__dirname, "./src/api") },
            { find: "assets", replacement: path.resolve(__dirname, "./src/assets") },
            { find: "components", replacement: path.resolve(__dirname, "./src/components") },
            { find: "contexts", replacement: path.resolve(__dirname, "./src/contexts") },
            { find: "forms", replacement: path.resolve(__dirname, "./src/forms") },
            { find: "hooks", replacement: path.resolve(__dirname, "./src/hooks") },
            { find: "icons", replacement: path.resolve(__dirname, "./src/icons") },
            { find: "pages", replacement: path.resolve(__dirname, "./src/pages") },
            { find: "route", replacement: path.resolve(__dirname, "./src/route") },
            { find: "stores", replacement: path.resolve(__dirname, "./src/stores") },
            { find: "utils", replacement: path.resolve(__dirname, "./src/utils") },
            { find: "Routes", replacement: path.resolve(__dirname, "./src/Routes") },
            {
                find: "serviceWorkerRegistration",
                replacement: path.resolve(__dirname, "./src/serviceWorkerRegistration"),
            },
            { find: "styles", replacement: path.resolve(__dirname, "./src/styles") },
            { find: "@local/shared", replacement: path.resolve(__dirname, "../shared/src") },
        ],
    },
});
